MarketPlace.web/Areas/Store/Controllers/ProductDiscountController.cs
using GoogleReCaptcha.V3.Interface;
using MarketPlace.application.Services.Interfaces;
using MarketPlace.dataLayer.DTOs.Discount;
using MarketPlace.web.Utilities;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace MarketPlace.web.Areas.Store.Controllers
{
    public class ProductDiscountController : StoreBaseController
    {
        private readonly IDiscountService _discountService;
        private readonly IStoreService _storeService;
        private readonly ICaptchaValidator _captchaValidator;
        public ProductDiscountController(IDiscountService discountService, IStoreService storeService, ICaptchaValidator captchaValidator)
        {
            _captchaValidator = captchaValidator;
            _discountService = discountService;
            _storeService = storeService;
        }
        [HttpGet("discounts")]
        public async Task<IActionResult> Index(FilterProductDiscountDto filter)
        {
            if (filter.ProductId == null || filter.ProductId < 1) return NotFound();
            var store = await _storeService.GetLastActiveStoreByUserId(User.UserId());
            filter.StoreId = store.Id;
            return View(await _discountService.FilterProductDiscount(filter));
        }

        [HttpGet("create-discount/{productId}")]
        public async Task<IActionResult> CreateProductDiscount(long productId)
        {
            return View(new CreateProductDiscountDto { 
            ProductId = productId
            });
        }
        [HttpPost("create-discount/{productId}"),AutoValidateAntiforgeryToken]
        public async Task<IActionResult> CreateProductDiscount(CreateProductDiscountDto discount)
        {
            if (!await _captchaValidator.IsCaptchaPassedAsync(discount.Captcha))
            {
                TempData[ErrorMessage] = "کپچا را به درستی وارد کنید";
                return View(discount);
            }
            if (ModelState.IsValid)
            {
                var store = await _storeService.GetLastActiveStoreByUserId(User.UserId());

                switch (await _discountService.CreateProductDiscount(discount,store.Id))
                {
                    case CreateProductDiscountResult.Success:
                        TempData[SuccessMessage] = "تخفیف با موفقیت افزوده شد";
                        return RedirectToAction("Index",new { ProductId=discount.ProductId});
                    case CreateProductDiscountResult.ProductIsNotAccess:
                        TempData[ErrorMessage] = "محصول یافت نشد";
                        return RedirectToAction("Index","Product");
                    case CreateProductDiscountResult.Error:
                        break;
                    default:
                        break;
                }
            }
            return View(discount);
        }
    }
}

MarketPlace.web/Areas/Store/Controllers/StoreWalletController.cs
using MarketPlace.application.Services.Interfaces;
using MarketPlace.dataLayer.DTOs.StoreWallet;
using MarketPlace.web.Utilities;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace MarketPlace.web.Areas.Store.Controllers
{
    public class StoreWalletController : StoreBaseController
    {
        private readonly IStoreWalletService _storeWalletService;
        private readonly IStoreService _storeService;

        public StoreWalletController(IStoreWalletService storeWalletService,IStoreService storeService)
        {
            _storeWalletService = storeWalletService;
            _storeService = storeService;
        }
        [HttpGet("wallet")]
        public async Task<IActionResult>Index(FilterStoreWalletDto filter)
        {
            var store =await _storeService.GetLastActiveStoreByUserId(User.UserId());
            if (store == null) return NotFound();
            filter.StoreId = store.Id;
            filter.TakeEntity = 15;
            return View(await _storeWalletService.FilterStoreWallet(filter));
        }
    }
}

MarketPlace.web/Areas/Store/Views/ProductDiscount/CreateProductDiscount.cshtml
@model MarketPlace.dataLayer.DTOs.Discount.CreateProductDiscountDto
@{
    ViewData["Title"] = "افزودن تخفیف";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@section styles{
<link rel="stylesheet" href="~/lib/date-picker/css/persianDatepicker-default.css" />
<link rel="stylesheet" href="~/lib/date-picker/css/persianDatepicker-dark.css" />
<link rel="stylesheet" href="~/lib/date-picker/css/persianDatepicker-latoja.css" />
<link rel="stylesheet" href="~/lib/date-picker/css/persianDatepicker-melon.css" />
<link rel="stylesheet" href="~/lib/date-picker/css/persianDatepicker-lightorang.css" />
}
 @section scripts{
    <partial name="_JqueryValidators" />
    <partial name="CaptchaScripts" />
  <script src="~/lib/date-picker/js/persianDatePicker.js"></script>
 <script>
     $(function() {
  $("#ExpireDate").persianDatepicker({theme:"dark",isRTL:true});
});

 </script>
 }




<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="/">خانه</a></li>
                        <li>@ViewData["Title"]  </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    <!-- Nav tabs -->
                    @await Component.InvokeAsync("StoreSideBar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade show active" id="account-details">
                            <h3>@ViewData["Title"]   </h3>
                            <div class="login">
                                <div class="login_form_container">
                                    <div class="account_login_form">
                                        <form asp-action="CreateProductDiscount" asp-area="Store" asp-controller="ProductDiscount">
                                            <partial name="_CaptchaInput" />
                                            <input type="hidden" asp-for="ProductId"/>
                                            <label>درصد</label>
                                            <input type="number" asp-for="Percentage">
                                            <span class="text-danger d-block mb-1" asp-validation-for="Percentage"></span>
                                               <label>تاریخ انقضا</label>
                                            <input type="text" asp-for="ExpireDate" style="width:100%">
                                            <span class="text-danger d-block mb-1" asp-validation-for="ExpireDate"></span>
                                               <label>ظرفیت</label>
                                            <input type="number" asp-for="DiscountNumberUsage">
                                            <span class="text-danger d-block mb-1" asp-validation-for="DiscountNumberUsage"></span>
                                          
                                            <div class="save_button primary_btn default_button">
                                                <button type="submit">ذخیره</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

MarketPlace.web/Areas/Store/Views/ProductDiscount/Index.cshtml
@using MarketPlace.application.Utils
@model MarketPlace.dataLayer.DTOs.Discount.FilterProductDiscountDto
@{
    ViewData["Title"] = "کد های تخفیف محصول";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
string NotFoundError = " کد تخفیفی یافت نشد";
}
 

<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="/">خانه</a></li>
                        <li>@ViewData["Title"]</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    @await Component.InvokeAsync("StoreSideBar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade active show" id="account-details">
                            <h3>@ViewData["Title"] </h3>
                            <div class="table-responsive">
                                <form id="filter-form" asp-area="Store" asp-controller="StoreWallet" asp-action="Index" method="get">
                                    <input type="hidden" asp-for="PageId"/>
                                </form>
                                @if (Model.ProductDiscounts != null && Model.ProductDiscounts.Any())
                                {
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>درصد</th>
                                                <th>ظرفیت باقی مانده</th>
                                                <th>تاریخ انقضا</th>
                                                <th>دستورات</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model.ProductDiscounts)
                                            {
                                                <tr>
                                                    <td>@item.Percentage </td>
                                                    <td>@item.DiscountNumberUsage</td>
                                                       <td> @item.ExpireDate.ToShamsiDate()</td>
                                                       <td>
                                                        
                                                    </td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                    <partial name="_SitePaging" model="@Model.GetCurrentPaging()"></partial>

                                }
            else
            {
                                    <partial name="_NoItemFound" model="@NotFoundError"/>
            }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
 