MarketPlace.web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarketPlace.web.Areas.Admin.Controllers
{
    public class HomeController : AdminBaseController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MarketPlace.web/Areas/Store/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace MarketPlace.web.Areas.Store.Controllers
{
    public class HomeController : StoreBaseController
    {
        public async Task<IActionResult>Index()
        {
             
            return View();
        }
    }
}

MarketPlace.web/Areas/User/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarketPlace.web.Areas.User.Controllers
{
    public class HomeController : UserBaseController
    {
        [HttpGet]
        public async Task<IActionResult> Dashbord()
        {
            return View();
        }
    }
}

MarketPlace.web/Areas/User/ViewComponents/UserSideBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarketPlace.web.Areas.User.ViewComponents
{
    public class UserSideBarViewComponent:ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("UserSideBar");
        }
    }
}

MarketPlace.web/Controllers/HomeController.cs
using GoogleReCaptcha.V3.Interface;
using MarketPlace.application.Extensions;
using MarketPlace.application.Services.Interfaces;
using MarketPlace.application.Utils;
using MarketPlace.dataLayer.DTOs.Contact;
using MarketPlace.dataLayer.Entities.Site;
using MarketPlace.web.Models;
using MarketPlace.web.Utilities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MarketPlace.web.Controllers
{
    public class HomeController : SiteBaseController
    {
        private readonly IContactService _contactService;
        private readonly ICaptchaValidator _captchaValidator;
        private readonly IProductService productService;
        private readonly ISiteService _siteService;
        private readonly IPaymentService _paymentService;
        public HomeController(IPaymentService paymentService,ISiteService siteService,IContactService contactService, ICaptchaValidator captchaValidator,IProductService productService)
        {
            _paymentService = paymentService;
            _siteService = siteService;
            _captchaValidator = captchaValidator;
            this.productService = productService;
            _contactService = contactService;
        }
        #region contactUs
        [HttpGet("contact-us")]
        public IActionResult ContactUS()
        {
            return View();
        }
        [HttpPost("contact-us")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ContactUS(CreateContactUsDto dto)
        {
            if (!await _captchaValidator.IsCaptchaPassedAsync(dto.Captcha))
            {
                TempData[ErrorMessage] = "کپچا را به درستی وارد کنید";
                return View(dto);
            }
            if (ModelState.IsValid)
            {
                await _contactService.CreateContactUs(dto,HttpContext.UserIP(),User.UserId());
                TempData[SuccessMessage] = "پیام شما با موفقیت ارسال شد";
                return Redirect("contact-us");
            }
            return View(dto);
        }
        #endregion
        #region index
        public async Task<IActionResult> Index(bool noPanel)
        {
            
            if (noPanel == true) { TempData[WarningMessage] = "شما پنل فروشندگی ندارید"; return Redirect("/"); };
            ViewBag.Banners =await _siteService.GetSiteBannerByPlacement(new List<BannerPlacement> {
              BannerPlacement.Home_1,
              BannerPlacement.Home_2,
              BannerPlacement.Home_3
            });
            ViewData["OffProducts"] = await productService.GetAllProductOffers(12);
            return View();
        }
        #endregion

        #region About us
        [HttpGet("about-us")]
        public async Task< IActionResult >AboutUS()
        {
            var siteSetting =await _siteService.GetDefaultSiteSetting();
            return View(siteSetting);
        }
        #endregion

        #region Upload ckEdito
        [HttpPost("Uploader/UploadImage")]
        public IActionResult UploadImage(IFormFile upload, string CKEditorFuncName, string CKEditor, string langCode)
        {
            if (upload.Length <= 0) return null;
            if (!upload.IsImage())
            {
                var notImageMessage = "لطفا یک تصویر انتخاب کنید";
                var notImage = JsonConvert.DeserializeObject("{'uploaded':0, 'error': {'message': \" " + notImageMessage + " \"}}");
                return Json(notImage);
            }

            var fileName = Guid.NewGuid() + Path.GetExtension(upload.FileName).ToLower();
            upload.AddImageToServer(fileName, PathExtension.UploadImageServer, null, null);
            return Json(new
            {
                uploaded = true,
                url = $"{PathExtension.UploadImage}{fileName}"
            });
        }
        #endregion

    }
}

MarketPlace.web/Areas/User/Views/Home/Dashbord.cshtml
@{
    ViewData["Title"] = "داشبورد";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="breadcrumbs_area">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_content">
                    <ul>
                        <li><a href="/">خانه</a></li>
                        <li>حساب کاربری</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<section class="main_content_area">
    <div class="container">
        <div class="account_dashboard">
            <div class="row">
                <div class="col-sm-12 col-md-3 col-lg-3">
                    <!-- Nav tabs -->
                 @await Component.InvokeAsync("UserSideBar")
                </div>
                <div class="col-sm-12 col-md-9 col-lg-9">
                    <!-- Tab panes -->
                    <div class="tab-content dashboard_content">
                        <div class="tab-pane fade show active" id="dashboard">
                            <h3>داشبورد </h3>
                            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با <a href="#">سفارشات اخیر</a>لورم ایپسوم متن <a href="#">لورم ایپسوم متن ساختگی با تولید</a> لورم <a href="#">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم</a></p>
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>