MarketPlace.web/Areas/Admin/Controllers/StoreController.cs
using MarketPlace.application.Services.Interfaces;
using MarketPlace.dataLayer.DTOs.Common;
using MarketPlace.dataLayer.DTOs.Store;
using MarketPlace.web.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MarketPlace.web.Areas.Admin.Controllers
{
    public class StoreController : AdminBaseController
    {
        private readonly IStoreService _storeService;
        public StoreController(IStoreService storeService)
        {
            _storeService = storeService;
        }
        #region Store Requests
        [HttpGet("store-requests")]
        public async Task<IActionResult> StoreRequests(FilterRequestStoreDto filter)
        {
            filter.TakeEntity =2;
            return View(await _storeService.FilterRequestStores(filter));
        }
        #endregion

        #region accept request
        [HttpGet("accept-request")]
        public async Task<IActionResult> AcceptStoreRequest(long requestId)
        {
            if (await _storeService.AcceptStoreRequest(requestId))
                return JsonResponeResult.SendStatus(JsonReqponseStatusType.Success, "درخواست با موفقیت تایید شد", null,true);
            else
                return JsonResponeResult.SendStatus(JsonReqponseStatusType.Error, "اطلاعاتی با این مشخصات یافت نشد", null, true);
        }
        #endregion 
        #region reject request
        [HttpPost("reject-request")]
        public async Task<IActionResult> RejectStoreRequest(RejectItemDto reject)
        {
            if (await _storeService.RejectStoreRequest(reject))
                return JsonResponeResult.SendStatus(JsonReqponseStatusType.Success, "درخواست با موفقیت رد شد", null, true);
            else
                return JsonResponeResult.SendStatus(JsonReqponseStatusType.Error, "اطلاعاتی با این مشخصات یافت نشد", null, true);
        }
        #endregion 
    }
}

MarketPlace.web/Controllers/ProductController.cs
using MarketPlace.application.Services.Interfaces;
using MarketPlace.dataLayer.DTOs.Store;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace MarketPlace.web.Controllers
{
    public class ProductController : SiteBaseController
    {
        private readonly IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        [HttpGet("product-list")]
        public async Task<IActionResult> FilterProducts(FilterProductsDto filter)
        {
            filter.FilterProductState = FilterProductState.Active;
            ViewBag.ProductCategories = await _productService.GetAllActiveProductCategories();
            filter.TakeEntity = 4;
            return View(await _productService.FilterProducts(filter));
        }
        [HttpGet("product-detail/{productId}")]
        public async Task<IActionResult> ProductDetail(long productId)
        { 
            var product = await _productService.GetProductDetail(productId);
            if (product == null) return NotFound();
            return View(product);
        }
    }
}

MarketPlace.web/Areas/Admin/Views/Shared/_AdminChatBarSection.cshtml
<!-- Chat Bar -->
<div id="chatbar" class="page-chatbar">
    <div class="chatbar-contacts">
        <div class="contacts-search">
            <input type="text" class="searchinput" placeholder="Search Contacts" />
            <i class="searchicon fa fa-search"></i>
            <div class="searchhelper">Search Your Contacts and Chat History</div>
        </div>
        <ul class="contacts-list">
            <li class="contact">
                <div class="contact-avatar">
                    <img src="~/AdminTemplate/img/avatars/divyia.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Divyia Philips</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        last week
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="~/AdminTemplate/img/avatars/Nicolai-Larson.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Adam Johnson</div>
                    <div class="contact-status">
                        <div class="offline"></div>
                        <div class="status">left 4 mins ago</div>
                    </div>
                    <div class="last-chat-time">
                        today
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="~/AdminTemplate/img/avatars/John-Smith.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">John Smith</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        1:57 am
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="~/AdminTemplate/img/avatars/Osvaldus-Valutis.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Osvaldus Valutis</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        today
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="~/AdminTemplate/img/avatars/Javi-Jimenez.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Javi Jimenez</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        today
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="~/AdminTemplate/img/avatars/Stephanie-Walter.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Stephanie Walter</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        yesterday
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="~/AdminTemplate/img/avatars/Sergey-Azovskiy.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Sergey Azovskiy</div>
                    <div class="contact-status">
                        <div class="offline"></div>
                        <div class="status">offline since oct 24</div>
                    </div>
                    <div class="last-chat-time">
                        22 oct
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="~/AdminTemplate/img/avatars/Lee-Munroe.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Lee Munroe</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        today
                    </div>
                </div>
            </li>
            <li class="contact">
                <div class="contact-avatar">
                    <img src="~/AdminTemplate/img/avatars/divyia.jpg" />
                </div>
                <div class="contact-info">
                    <div class="contact-name">Divyia Philips</div>
                    <div class="contact-status">
                        <div class="online"></div>
                        <div class="status">online</div>
                    </div>
                    <div class="last-chat-time">
                        last week
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="chatbar-messages" style="display: none;">
        <div class="messages-contact">
            <div class="contact-avatar">
                <img src="~/AdminTemplate/img/avatars/divyia.jpg" />
            </div>
            <div class="contact-info">
                <div class="contact-name">Divyia Philips</div>
                <div class="contact-status">
                    <div class="online"></div>
                    <div class="status">online</div>
                </div>
                <div class="last-chat-time">
                    a moment ago
                </div>
                <div class="back">
                    <i class="fa fa-arrow-circle-left"></i>
                </div>
            </div>
        </div>
        <ul class="messages-list">
            <li class="message">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Me</div>
                    <div class="message-time">10:14 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
            <li class="message reply">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Divyia</div>
                    <div class="message-time">10:15 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
            <li class="message">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Me</div>
                    <div class="message-time">10:14 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
            <li class="message reply">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Divyia</div>
                    <div class="message-time">10:15 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
            <li class="message">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Me</div>
                    <div class="message-time">10:14 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
            <li class="message reply">
                <div class="message-info">
                    <div class="bullet"></div>
                    <div class="contact-name">Divyia</div>
                    <div class="message-time">10:15 AM, Today</div>
                </div>
                <div class="message-body">
                    Hi, Hope all is good. Are we meeting today?
                </div>
            </li>
        </ul>
        <div class="send-message">
            <span class="input-icon icon-right">
                <textarea rows="4" class="form-control" placeholder="Type your message"></textarea>
                <i class="fa fa-camera themeprimary"></i>
            </span>
        </div>
    </div>
</div>
<!-- /Chat Bar -->

MarketPlace.web/Areas/Admin/Views/Shared/_AdminFooterReferences.cshtml
<!--Basic Scripts-->
<script src="~/AdminTemplate/js/jquery.min.js"></script>
<script src="~/AdminTemplate/js/bootstrap.min.js"></script>
<script src="~/AdminTemplate/js/slimscroll/jquery.slimscroll.min.js"></script>

<!--Beyond Scripts-->
<script src="~/AdminTemplate/js/skins.min.js"></script>
<script src="~/AdminTemplate/js/beyond.min.js"></script>


<!--Page Related Scripts-->
<!--Sparkline Charts Needed Scripts-->
<script src="~/AdminTemplate/js/charts/sparkline/jquery.sparkline.js"></script>
<script src="~/AdminTemplate/js/charts/sparkline/sparkline-init.js"></script>

<!--Easy Pie Charts Needed Scripts-->
<script src="~/AdminTemplate/js/charts/easypiechart/jquery.easypiechart.js"></script>
<script src="~/AdminTemplate/js/charts/easypiechart/easypiechart-init.js"></script>

<!--Flot Charts Needed Scripts-->
<script src="~/AdminTemplate/js/charts/flot/jquery.flot.js"></script>
<script src="~/AdminTemplate/js/charts/flot/jquery.flot.resize.js"></script>
<script src="~/AdminTemplate/js/charts/flot/jquery.flot.pie.js"></script>
<script src="~/AdminTemplate/js/charts/flot/jquery.flot.tooltip.js"></script>
<script src="~/AdminTemplate/js/charts/flot/jquery.flot.orderBars.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7/dist/sweetalert2.all.min.js"></script>
<script src="~/SiteTemplate/js/notifications.js"></script>
<script src="~/AdminTemplate/js/custom.js"></script>

<script>

    //Sets The Hidden Chart Width
    $('#dashboard-bandwidth-chart')
        .data('width', $('.box-tabbs')
            .width() - 20);
    //Visitor Sources Pie Chart
    var data = [
        {
            data: [[1, 21]],
            color: '#fb6e52'
        },
        {
            data: [[1, 12]],
            color: '#e75b8d'
        },
        {
            data: [[1, 11]],
            color: '#a0d468'
        },
        {
            data: [[1, 10]],
            color: '#ffce55'
        },
        {
            data: [[1, 46]],
            color: '#5db2ff'
        }
    ];
    var placeholder = $("#dashboard-pie-chart-sources");
    placeholder.unbind();

    $.plot(placeholder, data, {
        series: {
            pie: {
                innerRadius: 0.45,
                show: true,
                stroke: {
                    width: 4
                }
            }
        }
    });

    //Visit Chart (Main Chart)
    var data2 = [{
        color: themesecondary,
        label: "بازدید مستقیم",
        data: [[3, 2], [4, 5], [5, 4], [6, 11], [7, 12], [8, 11], [9, 8], [10, 14], [11, 12], [12, 16], [13, 9],
        [14, 10], [15, 14], [16, 15], [17, 9]],

        lines: {
            show: true,
            fill: true,
            lineWidth: .1,
            fillColor: {
                colors: [{
                    opacity: 0
                }, {
                    opacity: 0.4
                }]
            }
        },
        points: {
            show: false
        },
        shadowSize: 0
    },
    {
        color: themeprimary,
        label: "لینک از سایتها",
        data: [[3, 10], [4, 13], [5, 12], [6, 16], [7, 19], [8, 19], [9, 24], [10, 19], [11, 18], [12, 21], [13, 17],
        [14, 14], [15, 12], [16, 14], [17, 15]],
        bars: {
            order: 1,
            show: true,
            borderWidth: 0,
            barWidth: 0.4,
            lineWidth: .5,
            fillColor: {
                colors: [{
                    opacity: 0.4
                }, {
                    opacity: 1
                }]
            }
        }
    },
    {
        color: themethirdcolor,
        label: "موتورهای جستجو",
        data: [[3, 14], [4, 11], [5, 10], [6, 9], [7, 5], [8, 8], [9, 5], [10, 6], [11, 4], [12, 7], [13, 4],
        [14, 3], [15, 4], [16, 6], [17, 4]],
        lines: {
            show: true,
            fill: false,
            fillColor: {
                colors: [{
                    opacity: 0.3
                }, {
                    opacity: 0
                }]
            }
        },
        points: {
            show: true
        }
    }
    ];
    var options = {
        legend: {
            show: false
        },
        xaxis: {
            tickDecimals: 0,
            color: '#f3f3f3'
        },
        yaxis: {
            min: 0,
            color: '#f3f3f3',
            tickFormatter: function (val, axis) {
                return "";
            },
        },
        grid: {
            hoverable: true,
            clickable: false,
            borderWidth: 0,
            aboveData: false,
            color: '#fbfbfb'

        },
        tooltip: true,
        tooltipOpts: {
            defaultTheme: false,
            content: " <b>%x تیر ماه</b> , <b>%s</b> : <span>%y</span>",
        }
    };
    var placeholder = $("#dashboard-chart-visits");
    var plot = $.plot(placeholder, data2, options);

    //Real-Time Chart
    var realTimedata = [],
        realTimedata2 = [],
        totalPoints = 300;

    var getSeriesObj = function () {
        return [
            {
                data: getRandomData(),
                lines: {
                    show: true,
                    lineWidth: 1,
                    fill: true,
                    fillColor: {
                        colors: [
                            {
                                opacity: 0
                            }, {
                                opacity: 1
                            }
                        ]
                    },
                    steps: false
                },
                shadowSize: 0
            }, {
                data: getRandomData2(),
                lines: {
                    lineWidth: 0,
                    fill: true,
                    fillColor: {
                        colors: [
                            {
                                opacity: .5
                            }, {
                                opacity: 1
                            }
                        ]
                    },
                    steps: false
                },
                shadowSize: 0
            }
        ];
    };
    function getRandomData() {
        if (realTimedata.length > 0)
            realTimedata = realTimedata.slice(1);

        // Do a random walk

        while (realTimedata.length < totalPoints) {

            var prev = realTimedata.length > 0 ? realTimedata[realTimedata.length - 1] : 50,
                y = prev + Math.random() * 10 - 5;

            if (y < 0) {
                y = 0;
            } else if (y > 100) {
                y = 100;
            }
            realTimedata.push(y);
        }

        // Zip the generated y values with the x values

        var res = [];
        for (var i = 0; i < realTimedata.length; ++i) {
            res.push([i, realTimedata[i]]);
        }

        return res;
    }
    function getRandomData2() {
        if (realTimedata2.length > 0)
            realTimedata2 = realTimedata2.slice(1);

        // Do a random walk

        while (realTimedata2.length < totalPoints) {

            var prev = realTimedata2.length > 0 ? realTimedata[realTimedata2.length] : 50,
                y = prev - 25;

            if (y < 0) {
                y = 0;
            } else if (y > 100) {
                y = 100;
            }
            realTimedata2.push(y);
        }


        var res = [];
        for (var i = 0; i < realTimedata2.length; ++i) {
            res.push([i, realTimedata2[i]]);
        }

        return res;
    }
    // Set up the control widget
    var updateInterval = 500;
    var plot = $.plot("#dashboard-chart-realtime", getSeriesObj(), {
        yaxis: {
            color: '#f3f3f3',
            min: 0,
            max: 100,
            tickFormatter: function (val, axis) {
                return "";
            }
        },
        xaxis: {
            color: '#f3f3f3',
            min: 0,
            max: 100,
            tickFormatter: function (val, axis) {
                return "";
            }
        },
        grid: {
            hoverable: true,
            clickable: false,
            borderWidth: 0,
            aboveData: false
        },
        colors: ['#eee', themeprimary],
    });

    function update() {

        plot.setData(getSeriesObj());

        plot.draw();
        setTimeout(update, updateInterval);
    }
    update();


    //Initiates Easy Pie Chart instances in page
    InitiateEasyPieChart.init();

    //Initiates Sparkline Chart instances in page
    InitiateSparklineCharts.init();
</script>

MarketPlace.web/Areas/Admin/Views/Shared/_AdminHeaderReferences.cshtml
<link rel="shortcut icon" href="~/AdminTemplate/img/favicon.png" type="image/x-icon">

<!--Basic Styles-->
<link href="~/AdminTemplate/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/AdminTemplate/css/bootstrap-rtl.min.css" rel="stylesheet" />
<link href="~/AdminTemplate/css/font-awesome.min.css" rel="stylesheet" />
<link href="~/AdminTemplate/css/weather-icons.min.css" rel="stylesheet" />

<!--Fonts-->
<style>
    @@font-face {
        font-family: 'WYekan';
        src: url('/AdminTemplate/fonts/BYekan.woff') format('woff');
        font-weight: normal;
        font-style: normal;
    }
</style>
<link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">

<!--Beyond styles-->
<link href="~/AdminTemplate/css/beyond-rtl.min.css" rel="stylesheet" />
<link href="~/AdminTemplate/css/4095-rtl.min.css" rel="stylesheet" type="text/css" />
<link href="~/AdminTemplate/css/demo.min.css" rel="stylesheet" />
<link href="~/AdminTemplate/css/typicons.min.css" rel="stylesheet" />
<link href="~/AdminTemplate/css/animate.min.css" rel="stylesheet" />
<link rel=" stylesheet" href="~/SiteTemplate/css/notifications.css" />
<link id="skin-link" href="" rel="stylesheet" type="text/css" />

MarketPlace.web/Areas/Admin/Views/Shared/_AdminPaging.cshtml
@model MarketPlace.dataLayer.DTOs.Paging.BasePaging
<ul class="pagination">
    <li class="@(Model.StartPage<Model.PageId?"":"disabled")"><a onclick="FillPageId(@(Model.PageId-1))">«</a></li>
    @for (int i = Model.StartPage; i <= Model.EndPage; i++)
    {
        <li class="@(Model.PageId==i?"active":"")"><a onclick="FillPageId(@i)">@i</a></li>
    }
    <li class="@(Model.EndPage<Model.PageId?"disabled":"")"><a onclick="FillPageId(@(Model.PageId+1))">»</a></li>
</ul>
@*@(Model.PageId == i ? "<span class='sr-only'>(current)</span>":"")*@

MarketPlace.web/Areas/Admin/Views/Shared/_AdminSideBarSection.cshtml
<!-- Page Sidebar -->
            <div class="page-sidebar" id="sidebar">
                <!-- Page Sidebar Header-->
                <div class="sidebar-header-wrapper">
                    <input type="text" class="searchinput" />
                    <i class="searchicon fa fa-search"></i>
                    <div class="searchhelper">به جستجوی صفحات، گزارشات، پیام ها و ایمیل خود بپردازید</div>
                </div>
                <!-- /Page Sidebar Header -->
                <!-- Sidebar Menu -->
                <ul class="nav sidebar-menu">
                    <!--Dashboard-->
                    <li>
                        <a asp-area="Admin" asp-controller="Home" asp-action="Index">
                            <i class="menu-icon glyphicon glyphicon-home"></i>
                            <span class="menu-text"> داشبورد </span>
                        </a>
                    </li>
                    <li>
                        <a class="menu-dropdown">
                            <i class="menu-icon fa fa-user"></i>
                            <span class="menu-text">مدیریت فروشندگان </span>

                            <i class="menu-expand"></i>
                        </a>

                        <ul class="submenu">
                            <li>
                                <a asp-area="Admin" asp-controller="Store" asp-action="StoreRequests">
                                    <span class="menu-text">درخواست های فروشندگی  </span>
                                </a>
                            </li>
                              <li>
                                <a asp-area="Admin" asp-controller="Product" asp-action="Index">
                                    <span class="menu-text">درخواست های محصولات  </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" class="menu-dropdown">
                            <i class="menu-icon fa fa-desktop"></i>
                            <span class="menu-text"> عناصر گرافیکی </span>

                            <i class="menu-expand"></i>
                        </a>

                        <ul class="submenu">
                            <li>
                                <a href="elements.html">
                                    <span class="menu-text">عناصر عمومی</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="menu-dropdown">
                                    <span class="menu-text">
                                        آیکون ها
                                    </span>
                                    <i class="menu-expand"></i>
                                </a>

                                <ul class="submenu">
                                    <li>
                                        <a href="font-awesome.html">
                                            <i class="menu-icon fa fa-rocket"></i>
                                            <span class="menu-text">Font Awesome</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="glyph-icons.html">
                                            <i class="menu-icon glyphicon glyphicon-stats"></i>
                                            <span class="menu-text">Glyph Icons</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="typicon.html">
                                            <i class="menu-icon typcn typcn-location-outline"></i>
                                            <span class="menu-text"> Typicons</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="weather-icons.html">
                                            <i class="menu-icon wi wi-hot"></i>
                                            <span class="menu-text">Weather Icons</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="tabs.html">
                                    <span class="menu-text">زبانه ها و آکوردئون ها</span>
                                </a>
                            </li>
                            <li>
                                <a href="alerts.html">
                                    <span class="menu-text">هشدارها و راهنماها</span>
                                </a>
                            </li>
                            <li>
                                <a href="modals.html">
                                    <span class="menu-text">مدال و Wells</span>
                                </a>
                            </li>
                            <li>
                                <a href="buttons.html">
                                    <span class="menu-text">دکمه ها</span>
                                </a>
                            </li>
                            <li>
                                <a href="nestable-list.html">
                                    <span class="menu-text"> لیست های تو در تو</span>
                                </a>
                            </li>
                            <li>
                                <a href="treeview.html">
                                    <span class="menu-text">درخت ها</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <!-- /Sidebar Menu -->
            </div>
            <!-- /Page Sidebar -->

MarketPlace.web/Areas/Admin/Views/Shared/_RejectItem.cshtml
@model MarketPlace.dataLayer.DTOs.Common.RejectItemDto

<div class="form-group">
    <label class="definpu">شرح رد</label>
    <textarea class="form-control" asp-for="RejectMessage" rows="10"></textarea>
    <span asp-validation-for="RejectMessage" style="display:block; margin:10px" class="d-block text-danger"></span>
    <input type="hidden" asp-for="Id" />
    <button class="btn btn-sm btn-danger shiny" type="submit">رد درخواست</button>
</div>